# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: []
custom:
  - https://donate.stripe.com/00wfZacOdd2y5vG0XE14401
  - https://donate.stripe.com/fZubIUdSh3rY2jubCi14402
  - https://donate.stripe.com/6oUdR23dDgeK8HSaye14403
  - https://donate.stripe.com/28EfZa5lL4w29LW7m214404
  - https://donate.stripe.com/4gM4gs3dDd2y7DO5dU14405
